config.py, config.yml.sample, flocker_bb/zulip.py, flocker_bb/zulip_status.py
=> Allow logging to zulip.

config.py, slave/vagrant/boto-config.in, slave/vagrant/fabfile.py, slave/vagrant/fedora-vagrant-slave.service
https://clusterhq.atlassian.net/browse/FLOC-1071
=> [FLOC-1071] Document vagrant slave setup.

Dockerfile, config.py, flocker_bb/builders/flocker_vagrant.py, flocker_bb/buildset_status.py, flocker_bb/github.py
https://clusterhq.atlassian.net/browse/FLOC-1088
The results can be seen [here](https://github.com/ClusterHQ/flocker/compare/test-commit).
=> [FLOC-1088] Use mulitple github statuses.

flocker_bb/builders/flocker.py
https://clusterhq.atlassian.net/browse/FLOC-1226
=> Make linkcheck builder warn.

Dockerfile, buildbot.tac, config.py, flocker_bb/ec2.py, flocker_bb/ec2_buildslave.py, flocker_bb/eliot.py, flocker_bb/monkeypatch.py, templates/builders.html
https://clusterhq.atlassian.net/browse/FLOC-1201
See [here](https://github.com/ClusterHQ/build.clusterhq.com/pull/48/files#diff-daf3bae68c71021eb3d4e5ef58ca05bdR21) for a discussion of the implementation.
=> [FLOC-1201] Implement a latent slave that bypasses buildbot.

flocker_bb/steps.py, flocker_bb/test/test_steps.py
https://clusterhq.atlassian.net/browse/FLOC-1251
=> [FLOC-1251] Release branch merging.

config.py, flocker_bb/buildset_status.py, flocker_bb/github.py, flocker_bb/zulip_status.py
https://clusterhq.atlassian.net/browse/FLOC-1369
=> [FLOC-1369] Make build failures on master noisy.

config.py, flocker_bb/ec2.py, flocker_bb/ec2_buildslave.py, flocker_bb/monitoring.py
https://clusterhq.atlassian.net/browse/FLOC-1481
=> [FLOC-1481] Notice slave disconnect

slave/centos-7/cloud-init-base.sh, slave/cloud-init.sh, slave/fedora-20/cloud-init-base.sh, slave/ubuntu-14.04/cloud-init-base.sh
https://github.com/ClusterHQ/flocker/pull/1174#issuecomment-76504474
=> Get rid of mock on buildslaves.

config.py, fabfile.py, flocker_bb/builders/flocker.py, flocker_bb/builders/flocker_vagrant.py, flocker_bb/steps.py, slave/cloud-init.sh, slave/vagrant/fabfile.py
=> Run cloud acceptance tests on cloud machines.

slave/cloud-init.sh
https://clusterhq.atlassian.net/browse/FLOC-1787
=> [FLOC-1787] Populate AWS Cloud testing variables.

Dockerfile, config.py, config.yml.sample
Fixes https://clusterhq.atlassian.net/browse/FLOC-1940
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/build.clusterhq.com/88)
=> [FLOC-1940] buildmaster manhole

README.rst
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/build.clusterhq.com/82)
=> [FLOC-1942] Document workaround for Vagrant issue

flocker_bb/builders/flocker.py
Design for https://clusterhq.atlassian.net/browse/FLOC-1927
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/build.clusterhq.com/86)
=> [FLOC-1927] Generate a dedicated builder for each platform and supported OS

slave/pistoncloud/fabfile.py
Fixes: https://clusterhq.atlassian.net/browse/FLOC-1954
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/build.clusterhq.com/93)
=> [FLOC-1954] Fix some errors in the fabfile script.

flocker_bb/builders/flocker_vagrant.py
Merge this once https://github.com/ClusterHQ/flocker/pull/1380 has been merged in to Flocker master, to add a new builder for Ubuntu CLI tests
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/build.clusterhq.com/87)
=> [FLOC-1748] Add Ubuntu CLI test

flocker_bb/builders/flocker_vagrant.py
https://clusterhq.atlassian.net/browse/FLOC-1948
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/build.clusterhq.com/90)
=> [FLOC-1948] Collect run-acceptance-tests logs.

flocker_bb/builders/flocker.py, flocker_bb/builders/flocker_vagrant.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/build.clusterhq.com/97)
=> [FLOC-2007] Raise test_ebs.py run parallelism from 1 to 2.

flocker_bb/builders/flocker_vagrant.py
Follow-up for https://clusterhq.atlassian.net/browse/FLOC-1510 (which sadly is already "Done" with corresponding changes in Flocker master@HEAD).
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/build.clusterhq.com/96)
=> [FLOC-1510] Adjust to CentOS 7-based tutorial box

flocker_bb/ec2_buildslave.py, flocker_bb/util.py
https://clusterhq.atlassian.net/browse/FLOC-1938
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/build.clusterhq.com/99)
=> [FLOC-1938] Shutdown slave before the instance.

Dockerfile, flocker_bb/ec2.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/build.clusterhq.com/101)
=> Add retrying on EC2 request limit exceeded.

flocker_bb/ec2.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/build.clusterhq.com/103)
=> Also retry with back-off on rackspace.

flocker_bb/builders/flocker_vagrant.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/build.clusterhq.com/104)
Ubuntu 15.04 will fail until https://github.com/ClusterHQ/flocker/pull/1588 is merged.
=> [FLOC-2260] Add AWS client testing

Dockerfile, flocker_bb/builders/maint.py
https://clusterhq.atlassian.net/browse/FLOC-1704
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/build.clusterhq.com/102)
=> [FLOC-1704] Cleanup acceptance test nodes.

flocker_bb/builders/flocker_vagrant.py
https://clusterhq.atlassian.net/browse/FLOC-253
quick fix to help with debugging trial runs on vagrant machines
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/build.clusterhq.com/112)
=> quick workaround to get the output of the test log from trial on vagrant

config.py, config.yml.sample, flocker_bb/builders/flocker.py, slave/cloud-init.sh
Also removes configuration, on the principle that functionality is an asset & code is a liability.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/build.clusterhq.com/113)
=> Remove coverall communication from coverage builder

fabfile.py, flocker_bb/builders/maint.py
Fixes https://clusterhq.atlassian.net/browse/FLOC-2288
Staged with some results here - http://167.114.65.174/boxes-flocker?branch=annotate-test-suite-volumes-FLOC-2288&num_builds=2
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/build.clusterhq.com/109)
=> [FLOC-2288] Destroy leaked volumes on clouds

templates/layout.html
Fixes https://clusterhq.atlassian.net/browse/FLOC-2602
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/build.clusterhq.com/115)
=> [FLOC-2602] Link to metrics

flocker_bb/builders/flocker.py, flocker_bb/steps.py, flocker_bb/test/test_steps.py
https://clusterhq.atlassian.net/browse/FLOC-2480
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/build.clusterhq.com/107)
=> [FLOC-2480] Add new-style doc versioning.

.gitignore, .travis.yml, Dockerfile, flocker_bb/test/test_ondemand.py, flocker_bb/test/test_steps.py, flocker_bb/test/test_zulip.py, requirements.txt, tox.ini
https://clusterhq.atlassian.net/browse/FLOC-2604
This also fixes the tests that were failing.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/build.clusterhq.com/116)
=> [FLOC-2604] Setup tox and travis.

flocker_bb/monitoring.py
https://clusterhq.atlassian.net/browse/FLOC-2610
We have better methods of handling this now.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/build.clusterhq.com/118)
=> [FLOC-2610] Remove zulip reporting of pending builds.

Dockerfile, tomprince-hybridlogic-fedora-20-x86_64.repo
https://clusterhq.atlassian.net/browse/FLOC-2609
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/build.clusterhq.com/119)
=> [FLOC-2609] Update base image to Fedora 22.

slave/promote-images
https://clusterhq.atlassian.net/browse/FLOC-2608
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/build.clusterhq.com/117)
=> [FLOC-2608] Fix promote images.

flocker_bb/builders/maint.py
Fixes https://clusterhq.atlassian.net/browse/FLOC-2743
Tested this on a staging deployment.  Cleanup build failed (that's a good thing) because these instances were destroyed:
```
[
{
"creation_time": "2015-07-28T14:46:27+00:00",
"id": "ef9f306e-2a95-489e-855e-807b4d733d52",
"name": "acceptance-test-buildbot-1",
"provider": "Rackspace Cloud (Next Gen)"
},
{
"creation_time": "2015-07-28T14:34:35+00:00",
"id": "e87fe499-0318-40f4-b4d5-20c97988dafe",
"name": "acceptance-test-buildbot-0",
"provider": "Rackspace Cloud (Next Gen)"
},
{
"creation_time": "2015-07-28T14:14:20+00:00",
"id": "20c06a62-454e-472b-bf80-e8907ac69f81",
"name": "acceptance-test-buildbot-1",
"provider": "Rackspace Cloud (Next Gen)"
},
{
"creation_time": "2015-07-28T14:04:26+00:00",
"id": …
```
=> [FLOC-2743] Note TERMINATED nodes as well as those that are RUNNING.

README.rst
Fixes https://clusterhq.atlassian.net/browse/FLOC-2818
This pretty much just documents what Richard did, and puts a note about a TTY issue we found when trying the command locally.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/build.clusterhq.com/127)
=> [FLOC-2818] Vagrant no space floc 2818

flocker_bb/builders/flocker.py
As discussed in [FLOC-2837](https://clusterhq.atlassian.net/browse/FLOC-2837), the coverage builder is failing because we can't download our fork of coverage-reporter. This patch addresses the problem by removing the coverage builder entirely.
The current buildbot config refers to the `flocker-coverage` builder as an expected failure. I'm pretty sure that will need to be removed before deploying a version with this patch.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/build.clusterhq.com/130)
=> [FLOC-2837] Remove the flocker-coverage builder

README.rst
Fixes https://clusterhq.atlassian.net/browse/FLOC-2927
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/build.clusterhq.com/134)
=> [FLOC-2927] Explain how to build PRs

README.rst, slave/centos-7/manifest.yml, slave/ubuntu-14.04/manifest.yml
Also tweak docs.
This has already been applied to production buildbot. 
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/build.clusterhq.com/135)
=> [FLOC-2945] Promote new images

slave/vagrant/fabfile.py
https://clusterhq.atlassian.net/browse/FLOC-2749
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/build.clusterhq.com/139)
=> Some fixes for installing new virtualenv on soyoustart machine.

README.rst
Fixes https://clusterhq.atlassian.net/browse/FLOC-2987
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/build.clusterhq.com/141)
=> Document slaveami floc 2987

scripts/analyze_failed_jobs/README.md, scripts/analyze_failed_jobs/action_plugins/parsejobs.py, scripts/analyze_failed_jobs/action_plugins/parsestdouts.py, scripts/analyze_failed_jobs/ansible.cfg, scripts/analyze_failed_jobs/files/globber.py, scripts/analyze_failed_jobs/inventory, scripts/analyze_failed_jobs/playbook.yml
A quick hack in Python and Ansible to download buildbot's failed jobs and parse their output
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/build.clusterhq.com/144)
=> [FLOC-3216] Added scripts to download and analyze failed tests

flocker_bb/builders/maint.py
It would be better to report and/or handle them, but at least ignoring them will allow other deletes to happen.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/build.clusterhq.com/147)
=> [FLOC-3451] Ignore errors cleaning up.

flocker_bb/builders/maint.py
Fixes https://clusterhq.atlassian.net/browse/FLOC-3478
=> [FLOC-3478] Faster volume cleanup 
