- Dockerfile
- flocker_bb/boxes.py
- flocker_bb/builders/flocker.py
- flocker_bb/builders/flocker_vagrant.py
- flocker_bb/monkeypatch.py
- flocker_bb/steps.py
- flocker_bb/test/test_steps.py
https://clusterhq.atlassian.net/browse/FLOC-1227
Previously, a triggered version would always try to merge against master. Now they will merge against the same version as the triggering build.
This also moves building repository metadata to the master, so multiple versions of packages can be access with yum or apt.
> [FLOC-1227] Propagate merge versions across triggers.

- slave/phantomjs/Dockerfile
- slave/phantomjs/README.txt
- slave/vagrant/fabfile.py
Fixes FLOC-1264
This has been tested with instructions detailed in https://clusterhq.atlassian.net/browse/FLOC-1402 on a Rackspace onmetal server. The test can be seen passing at http://54.213.252.97/builders/flocker%2Facceptance%2Fvagrant%2Ffedora-20/builds/3/steps/trial/logs/stdio.
> Fix phantomjs floc 1264

- README.rst
- config.yml.sample
- start-aws.py
The existing instructions for tesing Buildbot changes on a staging server are vague and fail to mention specific requirements (e.g. memory requirements). Create a script to automate the process of starting a staging server, and update the instructions to refer to it.
> [FLOC-1580] Staging script

- flocker_bb/builders/flocker.py
Fixes https://clusterhq.atlassian.net/browse/FLOC-1560
This restricts the test suite run by the OS X builder.  It runs only the tests for software that is necessary for the CLI - which is the only part of Flocker that needs to work on OS X.
The list of such tests is hard-coded.  It would be better to specify these tests some other way but this is at least a step in the right direction.
Temporarily this branch is staged at http://52.11.7.92/builders/flocker-osx-10.10
> Try running only the tests relevant to the client software.

- flocker_bb/builders/flocker_vagrant.py
https://clusterhq.atlassian.net/browse/FLOC-1951
This depends on https://github.com/ClusterHQ/flocker/pull/1439
Also, it change the names of all the acceptance tests (losing the history). We could fix this, but I'm not sure if it worth it.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/build.clusterhq.com/91)
> [FLOC-1951] Specify acceptance test backends.

- flocker_bb/builders/flocker_vagrant.py
This reads in logs created by https://clusterhq.atlassian.net/browse/FLOC-1941, which has been merged.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/build.clusterhq.com/98)
> [FLOC-1693] Read in remote logs written out by run-acceptance-tests.

- flocker_bb/builders/flocker_vagrant.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/build.clusterhq.com/105)
> Reduce number of concurrent builds to keep AWS rate limits from being hit

- flocker_bb/monitoring.py
- flocker_bb/steps.py
- flocker_bb/test/test_steps.py
- flocker_bb/test/test_util.py
- flocker_bb/util.py
https://clusterhq.atlassian.net/browse/FLOC-2598
I want to get overall information on how flaky our tests & build process are, so that I can measure the success of our attempts to fix them, and so that we can have some sort of objective measure of when to stop and pursue other priorities.
Probably the easiest way to do this is to measure the rate of failed master builds. 
The first graph at http://metrics.build.clusterhq.com/failures shows the overall rate of failed builds, but it includes builds for branches, many of which we wouldn't expect to pass. 
To be able to filter for just master builds, we need to include a `branch` label in the metrics. This branch does that.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on …
> Record branch with finished build information

- slave/build-images
- slave/centos-7/manifest.yml
- slave/ubuntu-14.04/manifest.yml
Fixes https://clusterhq.atlassian.net/browse/FLOC-2680
This changes the size of the root EBS volume available to instances booted from these AMIs.
I've generated new Ubuntu AMIs using this branch: ami-d1a6a4e1 and ami-65a7a555.  CentOS 7 AMIs can easily be done next.
Manual inspection reveals they indeed have the desired larger root volume.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/build.clusterhq.com/124)
> [FLOC-2680] Make the slave AMIs larger

- README.rst
- flocker_bb/builders/flocker.py
Flocker's setup.py no longer has doc and release targets.  Removing
them eliminates the warnings from test logs.
See http://build.clusterhq.com/builders/flocker-centos-7/builds/5710/steps/install-extras/logs/stdio for an example of these warnings (the second and third red lines in the log file).
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/build.clusterhq.com/126)
> [FLOC-2675] Remove uses of doc and release as setup targets.

- flocker_bb/builders/flocker_vagrant.py
When FLOC-2771 is merged, Flocker client tests will no longer be needed for different cloud platforms.  I have removed the provider field from client configurations, and the `provider` and `config-file` flags from the `run-client-tests` command.
For the client configuration, we also only need to install the non-dev requirements.  There were two different `getFlockerFactory` functions (one in `flocker.py` and one in `flocker_vagrant.py`, which did slightly different things. The one in `flocker-vagrant.py` always installed dev dependencies. To allow only installation of non-dev dependencies, and also to avoid future confusion, I have changed the code to use a single function defined in `flocker.py`, which does not install any dependencies.  Hence, all calls now install their dependencies as …
> [FLOC-2813] Support Docker client tests

- README.rst
The staging instructions were recently modified to remove the instructions to set the `docker_tag`, but the commands to create the image were not changed to create an image with a different tag (`latest`).
This means that the staging instructions are broken, as they will ignore the built image, and download the latest master image, not incorporating the desired feature branch changes.
This could be solved by reverting the change (adding the `docker_tag` instructions back in), or by modifying other commands to build an image tagged `latest`.  This PR chooses the former, since tagging a temporary, non-master image as `latest` may be confusing.
Also, combined the instructions for the `buildbot` stanza to avoid the user having to jump back and forth in the `staging.yml` configuration file. …
> [FLOC-2841] Fix staging tag

- README.rst
- slave/centos-7/cloud-init-base.sh
- slave/ubuntu-14.04/cloud-init-base.sh
Fixes https://clusterhq.atlassian.net/browse/FLOC-1057
With this change, Docker can be upgraded by re-generating AMIs.  The version installed by get.docker.com at the time the scripts are run will be installed on the AMI.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/build.clusterhq.com/133)
> [FLOC-1057] Upgrade Docker on slave AMIs

- slave/centos-7/manifest.yml
- slave/ubuntu-14.04/manifest.yml
https://clusterhq.atlassian.net/browse/FLOC-2988
The base-ami points to the base image used to bulid the AMI. Changing them to
point to the built image means that any new image will be built from the latest
built image, which is what is desired.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/build.clusterhq.com/136)
> [FLOC-2988] Revert self-referential base AMI change.

- slave/centos-7/cloud-init-base.sh
- slave/osx/fabfile.py
- slave/redhat-openstack/fabfile.py
- slave/ubuntu-14.04/cloud-init-base.sh
- slave/vagrant/fabfile.py
https://clusterhq.atlassian.net/browse/FLOC-2749
This upgrades the pip used by all the builders to match the one required by buildbot. It does this by upgrading virtualenv to a version that bundles the appropriate pip.
You can see that the appropriate pip is installed [here](http://build.staging.clusterhq.com/builders/flocker-docs/builds/5/steps/install-dependencies/logs/stdio) (for the ubuntu slave) or [here](http://build.staging.clusterhq.com/builders/flocker-centos-7/builds/4/steps/install-dependencies/logs/stdio) (for the centos slave).
I haven't applied the changes to OSX or soyoustart machine yet. (I'll do that once this branch is accepted).
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/build.cluste …
> [FLOC-2749] Upgrade pip on buildslaves.

- flocker_bb/builders/flocker_vagrant.py
The Buildbot client tests do not currently specify the Flocker version when calling the `admin/run-client-tests` script.  This hasn't been a problem in the past, as the client tests simply print out the package version, without checking it.
However, FLOC-2770 will introduce a change to check that the Flocker version in the downloaded package matches the requested Flocker package version.  If the Flocker version is not specified, then the latest installable version is used.
This PR changes Buildbot to specify the Flocker version explicitly in the test, allowing it to pass.
There is a Buildmaster running at http://52.88.231.250 to check the results of this change.
http://build.clusterhq.com/boxes-flocker?branch=check-release-packages-FLOC-2770 demonstrates that client tests fail with the …
> [FLOC-3028] Add version to run-client-tests command

- README.rst
- flocker_bb/builders/flocker_vagrant.py
Fixes https://clusterhq.atlassian.net/browse/FLOC-2871
This is how it fails on master on the regular Buildbot:
```
~$ vagrant box add http://build.clusterhq.com/results/vagrant/master/flocker-tutorial.json
==> box: Loading metadata for box 'http://build.clusterhq.com/results/vagrant/master/flocker-tutorial.json'
==> box: Adding box 'clusterhq/flocker-tutorial' (v1.4.0.331.gba3dcc8) for provider: virtualbox
box: Downloading: https://s3.amazonaws.com/clusterhq-dev-archive/vagrant/tutorial/flocker-tutorial-1.4.0+331.gba3dcc8.box
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.
The requested URL returned error: 403 Forbidden
~$
```
A builder is set up (for now) with this new code at 52.89.42.46
```
~$ …
```
> Quote vagrant floc 2871

- slave/centos-7/cloud-init-base.sh
- slave/ubuntu-14.04/cloud-init-base.sh
Make PyPy available on buildslaves. Add PyPy installation to the scripts that build the slaves.  This does not cause Buildbot to use PyPy. It just allows the Builders to be modified to use PyPy.
Hence, this patch has no effect on existing systems. It is possible, however, to change Builders to use "pypy" as a parameter instead of "python2.7" when creating the virtualenv.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/build.clusterhq.com/142)
> [FLOC-3123] Install PyPy on Ubuntu and CentOS buildslaves

- flocker_bb/builders/flocker.py
Fixes https://clusterhq.atlassian.net/browse/FLOC-2496
This has been tested by setting up a test buildbot at http://52.89.42.46, and adding a GitHub webhook for Flocker pushes (as the main buildmaster has). With this buildbot on the master branch, all pushes to an experimental branch triggered builds. With this buildbot on this branch pushes to an experimental branch did not trigger builds, but pushes to a branch named "release/EXPERIMENTAL-BRANCH" triggered builds. I did not push to Flocker's master and have deemed that case sufficiently trivial to not need testing (and I hope you agree).
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/build.clusterhq.com/145)
> [FLOC-2496] Don't build on every push to flocker

- flocker_bb/builders/flocker_vagrant.py
Will possibly cause fewer tests to fail. 
If that's the case, then we can gradually ramp up parallelism.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/clusterhq/build.clusterhq.com/146)
> [FLOC-3246] Only one run AWS test at a time
